-- Family leaderboard backend for zdeneklab.cz/nasobilka/
-- Run once in Supabase SQL Editor.

create table if not exists public.math_scores (
  id bigint generated by default as identity primary key,
  family_id uuid not null,
  player_name text not null,
  subject text not null,
  score integer not null,
  correct integer not null,
  wrong integer not null,
  answered integer not null,
  accuracy numeric(5,2) not null,
  best_streak integer not null,
  duration_seconds integer not null default 60,
  created_at timestamptz not null default now(),

  constraint math_scores_player_len check (char_length(trim(player_name)) between 1 and 14),
  constraint math_scores_subject check (subject in ('mul','add','sub','mix')),
  constraint math_scores_score check (score between 0 and 5000),
  constraint math_scores_correct check (correct between 0 and 120),
  constraint math_scores_wrong check (wrong between 0 and 120),
  constraint math_scores_answered check (answered between 1 and 120),
  constraint math_scores_counts check (answered = correct + wrong),
  constraint math_scores_accuracy check (accuracy between 0 and 100),
  constraint math_scores_streak check (best_streak between 0 and correct),
  constraint math_scores_duration check (duration_seconds = 60),
  constraint math_scores_score_plausible check (score <= correct * 20)
);

create index if not exists math_scores_family_subject_score_idx
on public.math_scores (family_id, subject, score desc, correct desc, created_at asc);

alter table public.math_scores enable row level security;

drop policy if exists "family leaderboard read" on public.math_scores;
create policy "family leaderboard read"
on public.math_scores
for select
to anon
using (family_id = 'b6e6a9f8-2df1-4f65-8a1b-61b9d4d7f42e'::uuid);

drop policy if exists "family leaderboard insert" on public.math_scores;
create policy "family leaderboard insert"
on public.math_scores
for insert
to anon
with check (
  family_id = 'b6e6a9f8-2df1-4f65-8a1b-61b9d4d7f42e'::uuid
  and duration_seconds = 60
  and answered = correct + wrong
  and score <= correct * 20
);

grant select, insert on public.math_scores to anon;
grant usage, select on sequence public.math_scores_id_seq to anon;

-- No update/delete permissions are granted to anonymous visitors.
